trigger:
- main  # Specify the branch you want to trigger the pipeline on

pool: MOSHE

steps:
- task: mvn compilation
  inputs:
    versionSpec: '11'

- script: 'mvn clean package'
  displayName: 'Maven Package'
