trigger:
- main  # Specify the branch you want to trigger the pipeline on
pool: MOSHE
stages:
- stage: build
  jobs:
  - job: buildingjob
    pool:
      name: MOSHE
    steps:
    - script: echo Hello World!
      displayName: 'Run a One Line Script'
- stage: test
  jobs:
  - job: testingjob
    pool:
      name: MOSHE
    steps:
    - script: echo Thammuluri Moshe
      displayName: 'Run as Thammuluri Moshe'

    