trigger:
- main  # Specify the branch you want to trigger the pipeline on
pool: MOSHE
stages:
- stage: build
  jobs:
  - job: building job
    steps:
    - build passed
- stage: test
  jobs:
  - job: testing job
    steps:
    - tested all cases

    