trigger:
- main  # Specify the branch you want to trigger the pipeline on

pool: MOSHE

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'

- script: 'mvn clean package'
  displayName: 'Maven Package'
